
services:
  mysqlbd:
    container_name: mysqlbd
    image: mysql:8
    restart: on-failure
    environment:
     MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/mysql/data:/var/lib/mysql


  kaddem-project:
    container_name: kaddem-project-image
    image: kaddem-project-image
    restart: on-failure
    ports:
      - "9090:9090"
    depends_on:
      - mysqlbd

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8050:8080
      - 50000:50000
    container_name: jenkins
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      JENKINS_OPTS: --argumentsRealm.roles.user=admin --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin
    volumes:
      - ./jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
